apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-slim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-slim
  template:
    metadata:
      labels:
        app: pod-slim
    spec:
      containers:
      - name: slim
        image: $image:$tag
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: service-slim
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: pod-slim

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-slim
spec:
  tls:
  - secretName: cert-slim
  rules:
  - host: $domain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: service-slim
            port:
              number: 80